package com.ithome.domain;

public class Notify {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFY.ID
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFY. informant
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    private Integer informant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFY.RECEIVER
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    private Integer receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFY.OUTERID
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    private Integer outerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFY.TYPE
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFY.GMT_CREATE
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFY.STATUS
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFY.NOTIFIRE_NAME
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    private String notifireName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFY.OUTER_TITLE
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    private String outerTitle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFY.ID
     *
     * @return the value of NOTIFY.ID
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFY.ID
     *
     * @param id the value for NOTIFY.ID
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFY. informant
     *
     * @return the value of NOTIFY. informant
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    public Integer getInformant() {
        return informant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFY. informant
     *
     * @param informant the value for NOTIFY. informant
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    public void setInformant(Integer informant) {
        this.informant = informant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFY.RECEIVER
     *
     * @return the value of NOTIFY.RECEIVER
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    public Integer getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFY.RECEIVER
     *
     * @param receiver the value for NOTIFY.RECEIVER
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    public void setReceiver(Integer receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFY.OUTERID
     *
     * @return the value of NOTIFY.OUTERID
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    public Integer getOuterid() {
        return outerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFY.OUTERID
     *
     * @param outerid the value for NOTIFY.OUTERID
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    public void setOuterid(Integer outerid) {
        this.outerid = outerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFY.TYPE
     *
     * @return the value of NOTIFY.TYPE
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFY.TYPE
     *
     * @param type the value for NOTIFY.TYPE
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFY.GMT_CREATE
     *
     * @return the value of NOTIFY.GMT_CREATE
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFY.GMT_CREATE
     *
     * @param gmtCreate the value for NOTIFY.GMT_CREATE
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFY.STATUS
     *
     * @return the value of NOTIFY.STATUS
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFY.STATUS
     *
     * @param status the value for NOTIFY.STATUS
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFY.NOTIFIRE_NAME
     *
     * @return the value of NOTIFY.NOTIFIRE_NAME
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    public String getNotifireName() {
        return notifireName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFY.NOTIFIRE_NAME
     *
     * @param notifireName the value for NOTIFY.NOTIFIRE_NAME
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    public void setNotifireName(String notifireName) {
        this.notifireName = notifireName == null ? null : notifireName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFY.OUTER_TITLE
     *
     * @return the value of NOTIFY.OUTER_TITLE
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    public String getOuterTitle() {
        return outerTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFY.OUTER_TITLE
     *
     * @param outerTitle the value for NOTIFY.OUTER_TITLE
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    public void setOuterTitle(String outerTitle) {
        this.outerTitle = outerTitle == null ? null : outerTitle.trim();
    }
}