package com.ithome.mapper;

import com.ithome.domain.Notify;
import com.ithome.domain.NotifyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface NotifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NOTIFY
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    long countByExample(NotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NOTIFY
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    int deleteByExample(NotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NOTIFY
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NOTIFY
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    int insert(Notify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NOTIFY
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    int insertSelective(Notify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NOTIFY
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    List<Notify> selectByExampleWithRowbounds(NotifyExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NOTIFY
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    List<Notify> selectByExample(NotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NOTIFY
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    Notify selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NOTIFY
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    int updateByExampleSelective(@Param("record") Notify record, @Param("example") NotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NOTIFY
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    int updateByExample(@Param("record") Notify record, @Param("example") NotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NOTIFY
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    int updateByPrimaryKeySelective(Notify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NOTIFY
     *
     * @mbg.generated Fri Mar 27 14:02:24 CST 2020
     */
    int updateByPrimaryKey(Notify record);
}